apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aurascale-fintech-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Oluwa-feranmi/aurascale-infra.git'
    targetRevision: HEAD
    path: 'charts/fintech-app' # Where your Helm chart lives
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true      # Delete things if I delete them in Git
      selfHeal: true   # If a dev changes things manually, fix it!