AWSTemplateFormatVersion: "2010-09-09"
Description: OIDC-Provider

Parameters:
  ProviderUrl:
    Type: String
    Description: URL of the OIDC provider
    Default: 
Resources:
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Ref ProviderUrl
      ClientIDList:
        - sts.amazonaws.com
      ThumbprintList:
        - 2b18947a6a9fc7764fd8b5fb18a863b0c6dac24f
